import {
  User,
  Project,
  Task,
  CRMClient,
  ServerTelemetry,
  ActivityItem,
  SystemAlert,
  SystemMetrics,
} from "../domain/types";

export const mockCurrentUser: User = {
  id: "u-1",
  name: "David Sarria",
  email: "david@sarriatech.com",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
  role: "ADMIN",
};

export const mockTeamMembers: User[] = [
  mockCurrentUser,
  {
    id: "u-2",
    name: "María Gómez",
    email: "maria@sarriatech.com",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
    role: "DEVELOPER",
  },
  {
    id: "u-3",
    name: "Carlos Ruiz",
    email: "carlos@sarriatech.com",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    role: "DESIGNER",
  },
  {
    id: "u-4",
    name: "Elena Torres",
    email: "elena@sarriatech.com",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80",
    role: "QA",
  },
];

export const mockMetrics: SystemMetrics = {
  activeProjects: 28,
  activeProjectsGrowth: 12,
  inProgressTasks: 43,
  inProgressTasksGrowth: 8,
  activeClients: 16,
  activeClientsGrowth: 5,
  monthlyRevenue: 24560,
  monthlyRevenueGrowth: 18,
  loggedHours: 342,
  loggedHoursGrowth: 9,
};

export const mockProjectsStatusDistribution = [
  { name: "En Desarrollo", count: 12, percentage: 42.9, color: "#6366f1" },
  { name: "En Diseño", count: 6, percentage: 21.4, color: "#3b82f6" },
  { name: "En Pruebas", count: 5, percentage: 17.9, color: "#10b981" },
  { name: "En Producción", count: 3, percentage: 10.7, color: "#f59e0b" },
  { name: "Finalizados", count: 2, percentage: 7.1, color: "#8b5cf6" },
];

export const mockProjects: Project[] = [
  {
    id: "p-1",
    code: "GNS",
    name: "GNS",
    category: "Sistema SaaS",
    status: "En Desarrollo",
    progress: 74,
    bannerUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
    technologies: ["Next.js", "TypeScript", "Prisma", "TailwindCSS"],
    clientName: "SarriaTech Internal",
    team: mockTeamMembers,
    hoursEstimated: 450,
    hoursReal: 310,
    currentVersion: "2.8.1",
    gitRepo: "github.com/sarriatech/gns-saas",
    serverDomain: "gns.sarriatech.com",
    updatedAt: "Hace 12 min",
  },
  {
    id: "p-2",
    code: "INV-PRO",
    name: "Inventario Pro",
    category: "Sistema de Inventarios",
    status: "En Desarrollo",
    progress: 65,
    bannerUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80",
    technologies: ["React", "Node.js", "MySQL", "Docker"],
    clientName: "Logística Global S.A.",
    team: [mockTeamMembers[0], mockTeamMembers[1]],
    hoursEstimated: 320,
    hoursReal: 210,
    currentVersion: "1.2.0",
    gitRepo: "github.com/sarriatech/inventario-pro",
    serverDomain: "inv.logisticaglobal.com",
    updatedAt: "Hace 45 min",
  },
  {
    id: "p-3",
    code: "CRM-INM",
    name: "CRM Inmobiliaria",
    category: "Gestión de Clientes",
    status: "En Diseño",
    progress: 38,
    bannerUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80",
    technologies: ["Next.js", "Figma", "TailwindCSS", "PostgreSQL"],
    clientName: "Grupo Inmobiliario Alfa",
    team: mockTeamMembers,
    hoursEstimated: 280,
    hoursReal: 95,
    currentVersion: "0.4.0",
    gitRepo: "github.com/sarriatech/crm-inmobiliaria",
    serverDomain: "crm.inmobiliariaalfa.com",
    updatedAt: "Hace 3 horas",
  },
  {
    id: "p-4",
    code: "LND-CONST",
    name: "Landing Constructora",
    category: "Landing Page",
    status: "En Pruebas",
    progress: 92,
    bannerUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=600&q=80",
    technologies: ["Next.js", "Framer Motion", "TailwindCSS"],
    clientName: "Constructora Horizon",
    team: [mockTeamMembers[0], mockTeamMembers[2]],
    hoursEstimated: 80,
    hoursReal: 74,
    currentVersion: "1.0.0-rc2",
    gitRepo: "github.com/sarriatech/landing-constructora",
    serverDomain: "constructorahorizon.com",
    updatedAt: "Hace 1 hora",
  },
];

export const mockRecentActivity: ActivityItem[] = [
  {
    id: "act-1",
    user: mockCurrentUser,
    action: "actualizó la versión 2.8.1 de",
    target: "GNS",
    timestamp: "Hace 12 minutos",
    type: "version",
  },
  {
    id: "act-2",
    user: mockTeamMembers[1],
    action: "completó la tarea Diseño de Dashboard en",
    target: "GNS",
    timestamp: "Hace 45 minutos",
    type: "task",
  },
  {
    id: "act-3",
    user: mockTeamMembers[0],
    action: "publicó la versión 1.2.0 de",
    target: "Inventario Pro",
    timestamp: "Hace 2 horas",
    type: "version",
  },
  {
    id: "act-4",
    user: mockTeamMembers[2],
    action: "creó un nuevo proyecto",
    target: "CRM Inmobiliaria",
    timestamp: "Hace 3 horas",
    type: "project",
  },
  {
    id: "act-5",
    user: mockCurrentUser,
    action: "Backup automático completado en",
    target: "Servidor Principal",
    timestamp: "Hace 5 horas",
    type: "server",
  },
];

export const mockServers: ServerTelemetry[] = [
  {
    id: "srv-1",
    name: "Servidor Principal",
    environment: "Producción",
    ip: "192.168.1.100",
    status: "ONLINE",
    cpu: 18,
    ram: 43,
    disk: 29,
  },
  {
    id: "srv-2",
    name: "Servidor Secundario",
    environment: "Staging",
    ip: "192.168.1.101",
    status: "ONLINE",
    cpu: 22,
    ram: 37,
    disk: 31,
  },
  {
    id: "srv-3",
    name: "Servidor de Backups",
    environment: "Backups",
    ip: "192.168.1.102",
    status: "ONLINE",
    cpu: 8,
    ram: 15,
    disk: 61,
  },
  {
    id: "srv-4",
    name: "Servidor de Desarrollo",
    environment: "Desarrollo",
    ip: "192.168.1.103",
    status: "ONLINE",
    cpu: 12,
    ram: 28,
    disk: 24,
  },
];

export const mockNextTasks: Task[] = [
  {
    id: "tsk-1",
    code: "GNS-104",
    title: "Implementar módulo de reportes",
    status: "Desarrollo",
    priority: "Alta",
    projectName: "GNS",
    assignee: mockCurrentUser,
    dueDate: "14 May",
    subtasksCount: 5,
    subtasksCompleted: 3,
  },
  {
    id: "tsk-2",
    code: "CRM-28",
    title: "Revisión de UI/UX",
    status: "Diseño",
    priority: "Media",
    projectName: "CRM Inmobiliaria",
    assignee: mockTeamMembers[2],
    dueDate: "15 May",
    subtasksCount: 4,
    subtasksCompleted: 2,
  },
  {
    id: "tsk-3",
    code: "INV-89",
    title: "Pruebas de carga",
    status: "Testing",
    priority: "Media",
    projectName: "Inventario Pro",
    assignee: mockTeamMembers[3],
    dueDate: "16 May",
    subtasksCount: 6,
    subtasksCompleted: 5,
  },
  {
    id: "tsk-4",
    code: "GNS-105",
    title: "Deploy a producción",
    status: "Deploy",
    priority: "Alta",
    projectName: "GNS",
    assignee: mockCurrentUser,
    dueDate: "17 May",
    subtasksCount: 3,
    subtasksCompleted: 1,
  },
];

export const mockSystemAlerts: SystemAlert[] = [
  {
    id: "alt-1",
    type: "warning",
    message: "Uso de CPU del servidor principal: 85%",
    timestamp: "Hace 10 min",
  },
  {
    id: "alt-2",
    type: "error",
    message: "Backup fallido en servidor secundario",
    timestamp: "Hace 1 hora",
  },
  {
    id: "alt-3",
    type: "info",
    message: "SSL expirará en 7 días: gns.sarriatech.com",
    timestamp: "Hace 3 horas",
  },
];

export const mockClients: CRMClient[] = [
  {
    id: "c-1",
    company: "Logística Global S.A.",
    contactName: "Roberto Gómez",
    email: "roberto@logisticaglobal.com",
    phone: "+57 300 123 4567",
    stage: "Ganado",
    value: 14500,
    lastInteraction: "Ayer",
  },
  {
    id: "c-2",
    company: "Grupo Inmobiliario Alfa",
    contactName: "Ana Martínez",
    email: "ana@inmobiliariaalfa.com",
    phone: "+57 311 987 6543",
    stage: "Propuesta",
    value: 22000,
    lastInteraction: "Hace 2 días",
  },
  {
    id: "c-3",
    company: "Constructora Horizon",
    contactName: "Carlos Morales",
    email: "cmorales@horizon.com",
    phone: "+57 315 444 5566",
    stage: "Ganado",
    value: 8500,
    lastInteraction: "Hace 3 horas",
  },
];
